name: CI
on:
    push:
      branches: [ main]
    pull_request:
      branches: [ main]
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
        - name: ⬇️ Checkout Code
          uses: actions/checkout@v5

        - name: 🐢 Setup Node
          uses: actions/setup-node@v5
          with:
            node-version: lts/*

        - name: 🏗️ Install Dependencies
          run: npm install

        - name: 🧪 Test
          run: SECRET_KEY=${{ secrets.SECRET_KEY }} npx wdio wdio.conf.js --cucumberOpts.tagExpression='@regression'

        - name: Upload Cucumber Report Artifact
          uses: actions/upload-artifact@v5
          if: ${{ !cancelled() }}
          with:
            name: cucumber-report
            path: .tmp/report
        
